const productsData = [
    {
        id: 1,
        name: "Flecha.",
        price: 6,
        description: "Una flecha común. Su eje fue tallado con la madera de un arbol robusto",
        img: "./images/products/Arrow.png",
        category:"armas",
    },
    {
        id: 2,
        name:"Flechas x10",
        price: 35,
        description: "Paquete de 10 flechas comunes",
        img:"./images/products/Arrow.png",
        category:"armas",
    },
    {
        id: 3,
        name:"Cold Darner",
        price: 10,
        description:"Esta libélula prefiere la fresca sombra de los árboles al calor del sol. Sus alas dispersan el calor de su cuerpo, se puede cocinar en un elixir de resistencia al calor.",
        img:"./images/products/Cold_Darner.png",
        category:"ingredientes",
    },
    {
        id: 4,
        name:"Electric Darner",
        price: 10,
        description:"Esta rara libélula solo aparece bajo la lluvia. Sus alas alejan la electricidad de su cuerpo. Cocínalo con partes de monstruos para obtener un elixir de resistencia a la electricidad.",
        img: "./images/products/Electric_Darner.png",
        category: "ingredientes",
    },
    {
        id: 5,
        name: "Fireproof Lizard",
        price: 25,
        description:"Este raro lagarto solo se puede encontrar en la región de Eldin. Sus escamas tienen propiedades resistentes al calor.",
        img:"./images/products/Fireproof_Lizard.png",
        category:"ingredientes",
    },
    {
        id: 6,
        name: "Hearty Lizard",
        price: 100,
        description:"Este raro lagarto vive en lo profundo de los bosques. Cuando se usan para hacer elixires, aumentan temporalmente tus corazones máximos",
        img:"./images/products/Hearty_Lizard.png",
        category:"ingredientes",
    },
    {
        id:7,
        name:"Hearty Radish",
        price:32,
        description:"Este abundante rábano es rico en compuestos analépticos que, cuando se cocina en un plato, aumenta temporalmente tus corazones máximos.",
        img:"./images/products/Hearty-Radish.png",
        category:"comestible",
    },
    {
        id:8,
        name:"Hightail Lizard",
        price:10,
        description:"Un lagarto encontrado en todo Hyrule. Cocínalo con partes de monstruos para obtener un elixir que aumenta la velocidad.",
        img:"./images/products/Hightail-Lizard.png",
        category:"ingredientes",
    },
    {
        id:9,
        name:"Hot-Footed Frog",
        price:10,
        description:"Una rana rápida que se puede encontrar saltando cerca del agua. Cocínalo con partes de monstruos para sacar su efecto de aumento de velocidad.",
        img:"./images/products/Hot-Footed-Frog.png",
        category:"ingredientes",
    },
    {
        id:10,
        name:"Octo Balloon",
        price:20,
        description:"Este órgano inflable de Octorok tiene mucha elevación, así que puedes conectarlos a los elementos que deseas que floten.",
        img:"./images/products/Octo-Balloon.png",
        category:"ingredientes",
    },
    {
        id:11,
        name:"Restless Cricket",
        price:10,
        description:"Un grillo muy enérgico. Cocínalo con partes de monstruos para crear un elixir de recuperación de resistencia.",
        img:"./images/products/Restless-Cricket.png",
        category:"ingredientes",
    },
    {
        id:12,
        name:"Smotherwing Butterfly",
        price:10,
        description:"Esta rara mariposa vive en regiones volcánicas. Su cuerpo contiene un líquido resistente al calor, se puede convertir en un elixir que ofrece resistencia a las llamas.",
        img:"./images/products/Smotherwing-Butterfly.png",
        category:"ingredientes",
    },
    {
        id:13,
        name:"Summerwing Butterfly",
        price:10,
        description:"Una mariposa que se encuentra en los bosques y llanuras. Sus alas absorben el calor del sol. Cocínalo con partes de monstruos para crear un elixir que te haga sentir cálido.",
        img:"./images/products/Summerwing-Butterfly.png",
        category:"ingredientes",
    },
    {
        id:14,
        name:"Sunset Firefly",
        price:10,
        description:"Estas luciérnagas brillan suavemente en la oscuridad. Cuando se cocina con partes de monstruos da como resultado un elixir que te permitirá moverte con más tranquilidad.",
        img:"./images/products/Sunset-Firefly.png",
        category:"ingredientes",
    },
    {
        id:15,
        name:"Swift Carrot",
        price:16,
        description:"Esta zanahoria se cultiva extensamente en la villa Kakariko. Cuando se cocina en un plato, lo que ayuda a aumentar la velocidad de movimiento.",
        img:"./images/products/Swift_Carrot.png",
        category:"comestible",
    },
    {
        id:16,
        name:"Thunderwing Butterfly",
        price:10,
        description:"Esta rara mariposa solo se muestra cuando llueve. Cuando se convierte en un elixir, ofrece resistencia eléctrica.",
        img:"./images/products/Thunderwing-Butterfly.png",
        category:"ingredientes",
    },
    {
        id:17,
        name:"Tireless Frog",
        price:100,
        description:"Esta rara rana solo se aventura bajo la lluvia. Cuando se cocina con partes de monstruos, el elixir que produce aumentará temporalmente tu resistencia máxima.",
        img:"./images/products/Tireless-Frog.png",
        category:"ingredientes",
    },
    {
        id:18,
        name:"Warm Darner",
        price:10,
        description:"Esta libélula tiene un órgano especial que la hace sudar profusamente. Cocínelo con partes de monstruos para obtener un elixir que elevará su temperatura central para que pueda resistir el frío.",
        img:"./images/products/Warm-Darner.png",
        category:"ingredientes",
    },
    {
        id:19,
        name:"Winterwing Butterfly",
        price:10,
        description:"Las escamas polvorientas de las alas de esta mariposa refrescan el aire a su alrededor. Cocínelo con partes de monstruos para obtener un elixir resistente al calor.",
        img:"./images/products/Winterwing-Butterfly.png",
        category:"ingredientes",
    }
 ]